name: <Native> Compile for OpenHarmony

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'
  release:
    types: [published]

jobs:
  compile_oh:
    name: "OpenHarmony"
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Get oh sdk cache directory path
        id: oh-sdk-cache-dir-path
        run: |
          echo "cache dir: "
          yarn cache dir
          echo "dir=$HOME/openharmony" >> $GITHUB_OUTPUT

      - name: Output cache dir
        run: |
          echo "Output cache dir: ${{ steps.oh-sdk-cache-dir-path.outputs.dir }}"

      - name: Cache OH SDK
        id: cache-oh-sdk
        uses: actions/cache@v3
        env:
          cache-name: cache-oh-sdk
        with:
          path: ${{ steps.oh-sdk-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Add package.json
        run: |
          echo "{}" > package.json
          echo "{\"name\": \"tests\",\"lockfileVersion\": 3,\"requires\": true,\"packages\": {}}" > package-lock.json
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - if: ${{ steps.cache-oh-sdk.outputs.cache-hit != 'true' }}
        name: List the state of oh sdk
        continue-on-error: false
        run: |
          if [ ! -d "$HOME/openharmony" ]; then
            mkdir -p $HOME/openharmony
            curl -o ohcommandline-tools-linux.zip "https://contentcenter-vali-drcn.dbankcdn.cn/pvt_2/DeveloperAlliance_package_901_9/94/v3/YAvJB7RcQg6sOu4z0eL0-g/ohcommandline-tools-linux-2.0.0.2.zip?HW-CC-KV=V1&HW-CC-Date=20230621T074901Z&HW-CC-Expire=315360000&HW-CC-Sign=8A0965E3B37FBA75D7FB8593DFE5B6537F4EA698467F3D0B5667D8AD360F7ACA"
            unzip ohcommandline-tools-linux.zip -d $HOME/openharmony
            cd $HOME/openharmony
            ls -l
            cd oh-command-line-tools/bin
            ./ohsdkmgr list
            echo "=============== INSTALL OH SDK ==============="
            ./ohsdkmgr install ets:9 js:9 native:9 toolchains:9 --accept-license
            echo "=============== INSTALL OH SDK DONE ==============="
            ./ohsdkmgr list
          fi

      - name: Compile for OpenHarmony
        run: |
          which node
          which npm
          which java
          node -v
          npm -v
          java --version
          echo "=============== SET NPM OH REGISTRY ==============="
          npm config set @ohos:registry=https://repo.harmonyos.com/npm/
          echo "=============== UPDATE local.properties ==============="
          echo "sdk.dir=$(pwd)/sdk/openharmony" > local.properties
          echo "nodejs.dir=/usr/local/bin" > local.properties
          echo "hwsdk.dir=$(pwd)/sdk" > local.properties
          echo "=============== EXECUTE hvigorw ==============="
          # ./hvigorw --mode module -p module=entry@default -p product=default -p debuggable=true assembleHap
          echo "=============== EXECUTE hvigorw DONE ==============="

          



